services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    environment:
      FOO: bar
      PHASE: day33-git
    labels:
      - devops.phase=day33-git
    ports:
      - 8082:80
    restart: always
