apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: prod-nginx
data:
  default.conf: |
    server {
      listen 80;
      gzip on;
      add_header X-Stage "day59-prod-nginx";
      add_header X-Pod "$hostname";
      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
      }
    }
