services:
  db:
    image: postgres:16
    container_name: pg-day6
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
    name: pgdata
